### ISSUE TITLE
Posible problem with the latest version of SoapySDR

### ISSUE THREAD

**Issue by daniel-dona** [dvdesolve/mlrpt#2] opened 2021-02-07 16:03 UTC
mlrpt version: GitHub master
SoapySDR: GitHub master (future 0.8.0 release) -> https://github.com/pothosware/SoapySDR/blob/master/Changelog.txt

Fails here:

```
[  3%] Building C object src/CMakeFiles/mlrpt.dir/sdr/SoapySDR.c.o
/home/dani/mlrpt/src/sdr/SoapySDR.c: In function ‘SoapySDR_Init’:
/home/dani/mlrpt/src/sdr/SoapySDR.c:506:12: warning: passing argument 2 of ‘SoapySDRDevice_setupStream’ makes integer from pointer without a cast [-Wint-conversion]
       sdr, &rxStream, SOAPY_SDR_RX, SOAPY_SDR_CS16, NULL, 0, NULL );
            ^
In file included from /home/dani/mlrpt/src/sdr/SoapySDR.c:23:0:
/usr/local/include/SoapySDR/Device.h:295:31: note: expected ‘int’ but argument is of type ‘SoapySDRStream ** {aka struct SoapySDRStream **}’
 SOAPY_SDR_API SoapySDRStream *SoapySDRDevice_setupStream(SoapySDRDevice *device,
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/dani/mlrpt/src/sdr/SoapySDR.c:506:23: warning: passing argument 3 of ‘SoapySDRDevice_setupStream’ makes pointer from integer without a cast [-Wint-conversion]
       sdr, &rxStream, SOAPY_SDR_RX, SOAPY_SDR_CS16, NULL, 0, NULL );
                       ^~~~~~~~~~~~
In file included from /home/dani/mlrpt/src/sdr/SoapySDR.c:23:0:
/usr/local/include/SoapySDR/Device.h:295:31: note: expected ‘const char *’ but argument is of type ‘int’
 SOAPY_SDR_API SoapySDRStream *SoapySDRDevice_setupStream(SoapySDRDevice *device,
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/dani/mlrpt/src/sdr/SoapySDR.c:506:37: warning: passing argument 4 of ‘SoapySDRDevice_setupStream’ from incompatible pointer type [-Wincompatible-pointer-types]
       sdr, &rxStream, SOAPY_SDR_RX, SOAPY_SDR_CS16, NULL, 0, NULL );
                                     ^~~~~~~~~~~~~~
In file included from /home/dani/mlrpt/src/sdr/SoapySDR.c:23:0:
/usr/local/include/SoapySDR/Device.h:295:31: note: expected ‘const size_t * {aka const long unsigned int *}’ but argument is of type ‘char *’
 SOAPY_SDR_API SoapySDRStream *SoapySDRDevice_setupStream(SoapySDRDevice *device,
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/dani/mlrpt/src/sdr/SoapySDR.c:506:53: warning: passing argument 5 of ‘SoapySDRDevice_setupStream’ makes integer from pointer without a cast [-Wint-conversion]
       sdr, &rxStream, SOAPY_SDR_RX, SOAPY_SDR_CS16, NULL, 0, NULL );
                                                     ^~~~
In file included from /home/dani/mlrpt/src/sdr/SoapySDR.c:23:0:
/usr/local/include/SoapySDR/Device.h:295:31: note: expected ‘size_t {aka const long unsigned int}’ but argument is of type ‘void *’
 SOAPY_SDR_API SoapySDRStream *SoapySDRDevice_setupStream(SoapySDRDevice *device,
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/dani/mlrpt/src/sdr/SoapySDR.c:505:9: error: too many arguments to function ‘SoapySDRDevice_setupStream’
   ret = SoapySDRDevice_setupStream(
         ^~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/dani/mlrpt/src/sdr/SoapySDR.c:23:0:
/usr/local/include/SoapySDR/Device.h:295:31: note: declared here
 SOAPY_SDR_API SoapySDRStream *SoapySDRDevice_setupStream(SoapySDRDevice *device,
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/dani/mlrpt/src/sdr/SoapySDR.c:505:7: warning: assignment makes integer from pointer without a cast [-Wint-conversion]
   ret = SoapySDRDevice_setupStream(
       ^
src/CMakeFiles/mlrpt.dir/build.make:393: fallo en las instrucciones para el objetivo 'src/CMakeFiles/mlrpt.dir/sdr/SoapySDR.c.o'
make[2]: *** [src/CMakeFiles/mlrpt.dir/sdr/SoapySDR.c.o] Error 1
CMakeFiles/Makefile2:172: fallo en las instrucciones para el objetivo 'src/CMakeFiles/mlrpt.dir/all'
make[1]: *** [src/CMakeFiles/mlrpt.dir/all] Error 2
Makefile:148: fallo en las instrucciones para el objetivo 'all'
make: *** [all] Error 2
```

**Comment by dvdesolve** [comment] 2021-02-07 16:05
Yep, the same problem is observed with glrpt. Latest stable version is 0.7.2 and I'd recommend to use it for now. As soon as stable 0.8 will be released we'll incorporate proper changes

**Comment by daniel-dona** [comment] 2021-02-07 16:06
Wow, that was fast! Thank you so much!

**Comment by dvdesolve** [comment] 2021-02-07 16:08
I think because the problem is the same for both mlrpt and glrpt it's better to track progress [here](https://github.com/dvdesolve/glrpt/issues/7)

**Closed as completed by dvdesolve** 2021-02-07 16:08 UTC
